# Generated by Django 4.0.6 on 2022-07-17 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
