# Generated by Django 4.0.6 on 2022-07-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_file_key_delete_fileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='username',
            new_name='custom_filename',
        ),
    ]
