# Generated by Django 4.0.6 on 2022-07-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_username_file_custom_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='enckey',
        ),
    ]
