# Generated by Django 4.0.6 on 2022-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_file_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='filename',
            field=models.FileField(default='', upload_to='upload/%Y%m%d'),
        ),
    ]
