# Generated by Django 4.0.6 on 2022-08-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_file_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='key',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='key',
            name='filename',
            field=models.FileField(default='', upload_to='upload/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='key',
            name='session_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default='', max_length=256),
        ),
    ]
