# Generated by Django 4.0.6 on 2022-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_key_public_key_remove_key_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='en_sha256',
            field=models.CharField(default=' ', max_length=256),
        ),
    ]
