# Generated by Django 4.0.6 on 2022-08-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_key_sign_key_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='username',
            new_name='user_name',
        ),
    ]
