# Generated by Django 4.0.6 on 2022-08-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_username_key_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='user_name',
        ),
    ]
