# Generated by Django 4.0.6 on 2022-08-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_key_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret_key',
            field=models.CharField(default='', max_length=256),
        ),
    ]
