# Generated by Django 4.0.6 on 2022-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_file_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='keynumber',
            field=models.CharField(default='', max_length=16),
        ),
    ]
