# Generated by Django 4.0.6 on 2022-08-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('filename', models.FileField(upload_to='upload/%Y%m%d')),
                ('share_numbers', models.IntegerField(default=0)),
                ('remain_numbers', models.IntegerField(default=0)),
            ],
        ),
    ]
