# Generated by Django 4.0.6 on 2022-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_key_en_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='sign',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='key',
            name='username',
            field=models.CharField(default='', max_length=128, unique='False'),
        ),
    ]
